[tool.poetry]
name = "iam-util"
version = "0.1.0"
description = "AWS IAM utility"
authors = ["ethanoic <ethan.ccj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
